#Google drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
import pandas as pd

In [ ]:
score_sum_path = '/content/drive/MyDrive/share_drive/박박박사/Score_sum'

#Score

In [ ]:
base_score_directory = '/content/drive/MyDrive/share_drive/박박박사/Score_sum'

base_score_1 = os.path.join(base_score_directory, 'Hyundai_score_sum_holiday.csv')
base_score_2 = os.path.join(base_score_directory, 'Kbfg_score_sum_holiday.csv')
base_score_3 = os.path.join(base_score_directory, 'Kia_score_sum_holiday.csv')
base_score_4 = os.path.join(base_score_directory, 'Lgchem_score_sum_holiday.csv')
base_score_5 = os.path.join(base_score_directory, 'Lgensol_score_sum_holiday.csv')
base_score_6 = os.path.join(base_score_directory, 'Naver_score_sum_holiday.csv')
base_score_7 = os.path.join(base_score_directory, 'PoscoHoldings_score_sum_holiday.csv')
base_score_8 = os.path.join(base_score_directory, 'SamsungBiologics_score_sum_holiday.csv')
base_score_9 = os.path.join(base_score_directory, 'Samsung_score_sum_holiday.csv')
base_score_10 = os.path.join(base_score_directory, 'Skhynix_score_sum_holiday.csv')

In [ ]:
df_score_Hyundai = pd.read_csv(base_score_1)
df_score_Kbfg = pd.read_csv(base_score_2)
df_score_Kia = pd.read_csv(base_score_3)
df_score_Lgchem = pd.read_csv(base_score_4)
df_score_Lgensol = pd.read_csv(base_score_5)
df_score_Naver = pd.read_csv(base_score_6)
df_score_PoscoHoldings = pd.read_csv(base_score_7)
df_score_SamsungBiologics = pd.read_csv(base_score_8)
df_score_Samsung = pd.read_csv(base_score_9)
df_score_Skhynix = pd.read_csv(base_score_10)

In [ ]:
df_score_Hyundai.head()

           날짜   점수        요일  공휴일여부
0  2022-01-27  109  Thursday      0
1  2022-01-28   73    Friday      0
2  2022-01-29   12  Saturday      0
3  2022-01-30    5    Sunday      0
4  2022-01-31   18    Monday      1

In [ ]:
dataframes_to_save = {
    "df_score_Hyundai": df_score_Hyundai,
    "df_score_Kbfg": df_score_Kbfg,
    "df_score_Kia": df_score_Kia,
    "df_score_Lgchem": df_score_Lgchem,
    "df_score_Lgensol": df_score_Lgensol,
    "df_score_Naver": df_score_Naver,
    "df_score_PoscoHoldings": df_score_PoscoHoldings,
    "df_score_SamsungBiologics": df_score_SamsungBiologics,
    "df_score_Samsung": df_score_Samsung,
    "df_score_Skhynix": df_score_Skhynix,
}

In [ ]:
output_base_dir = '/content/drive/MyDrive/dataset'
df_score_folder = os.path.join(output_base_dir, 'df_score')

if not os.path.exists(df_score_folder):
    os.makedirs(df_score_folder)

In [ ]:
for df_name, df in dataframes_to_save.items():
    df_path = os.path.join(df_score_folder, f"{df_name}.csv")
    df.to_csv(df_path, index=False, encoding='utf-8-sig')

#1군

In [ ]:
base_first_directory = '/content/drive/MyDrive/share_drive/박박박사/뉴스기사/1군'

base_first_1 = os.path.join(base_first_directory, '현대자동차1군.csv')
base_first_2 = os.path.join(base_first_directory, 'KB금융 1군.csv')
base_first_3 = os.path.join(base_first_directory, '기아1군.csv')
base_first_4 = os.path.join(base_first_directory, 'LG화학 1군.csv')
base_first_5 = os.path.join(base_first_directory, 'LG에너지솔루션1군.csv')
base_first_6 = os.path.join(base_first_directory, '네이버1군.csv')
base_first_7 = os.path.join(base_first_directory, 'POSCO홀딩스1군.csv')
base_first_8 = os.path.join(base_first_directory, '삼성바이오로직스1군.csv')
base_first_9 = os.path.join(base_first_directory, '삼성전자1군.csv')
base_first_10 = os.path.join(base_first_directory, 'SK하이닉스1군.csv')

In [ ]:
df_first_Hyundai = pd.read_csv(base_first_1)
df_first_Kbfg = pd.read_csv(base_first_2)
df_first_Kia = pd.read_csv(base_first_3)
df_first_Lgchem = pd.read_csv(base_first_4)
df_first_Lgensol = pd.read_csv(base_first_5)
df_first_Naver = pd.read_csv(base_first_6)
df_first_PoscoHoldings = pd.read_csv(base_first_7)
df_first_SamsungBiologics = pd.read_csv(base_first_8)
df_first_Samsung = pd.read_csv(base_first_9)
df_first_Skhynix = pd.read_csv(base_first_10)

In [ ]:
df_first_Hyundai.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3360 entries, 0 to 3359
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   뉴스 식별자             3360 non-null   float64
 1   일자                 3360 non-null   int64
 2   언론사                3360 non-null   object
 3   기고자                3295 non-null   object
 4   제목                 3360 non-null   object
 5   통합 분류1             3360 non-null   object
 6   통합 분류2             2886 non-null   object
 7   통합 분류3             2210 non-null   object
 8   사건/사고 분류1          294 non-null    object
 9   사건/사고 분류2          59 non-null     object
 10  사건/사고 분류3          17 non-null     object
 11  인물                 1436 non-null   object
 12  위치                 2641 non-null   object
 13  기관                 3358 non-null   object
 14  키워드                3360 non-null   object
 15  특성추출(가중치순 상위 50개)  3360 non-null   object
 16  본문                 3360 non-null   object
 17  URL                3356 non-null   object
 18  분석제외 여부            412 non-null    object
dtypes: float64(1), int64(1), object(17)
memory usage: 498.9+ KB

**[colums_to_keep] : 해당 col에 대한 값 외에는 drop하지 않는 방법**

In [ ]:
columns_to_keep = ['일자', '제목', '키워드', '본문']

In [ ]:
df_first_Hyundai = pd.read_csv(base_first_1)[columns_to_keep]
df_first_Hyundaidf_first_Kbfg = pd.read_csv(base_first_2)[columns_to_keep]
df_first_Kia = pd.read_csv(base_first_3)[columns_to_keep]
df_first_Lgchem = pd.read_csv(base_first_4)[columns_to_keep]
df_first_Lgensol = pd.read_csv(base_first_5)[columns_to_keep]
df_first_Naver = pd.read_csv(base_first_6)[columns_to_keep]
df_first_PoscoHoldings = pd.read_csv(base_first_7)[columns_to_keep]
df_first_SamsungBiologics = pd.read_csv(base_first_8)[columns_to_keep]
df_first_Samsung = pd.read_csv(base_first_9)[columns_to_keep]
df_first_Skhynix = pd.read_csv(base_first_10)[columns_to_keep]

In [ ]:
df_first_Hyundai.head()

,일자,제목,키워드,본문
0,20241230,"[비즈투데이] 현대자동차 기아, '글로벌 통합 탄소 배출 정보 시스템' 구축","현대자동차,기아,정보,글로벌,통합,탄소,배출,정보,구축,현대자동차ㆍ기아,정보,글로벌...","현대자동차ㆍ기아가 '글로벌 통합 탄소 배출 정보 시스템'(IGIS)을 구축하고, 탄..."
1,20241230,올해 증시 혼조세로 마감...1년간 환율 180원 올라,"증시,마감,1년,환율,증시,혼조세,마감,코스피시장,코스피,0.22%,하락,2,399...",올해 우리 증시가 혼조세로 마감했습니다.\n\n코스피시장에서 코스피는 0.22% 하...
2,20241227,충주시 “수소버스 사고 수습 점검 강화”,"충주시,수소버스,사고,수습,점검,강화,충주,충전소,사고,버스,폭발,충주시,점검,안전...","[KBS 청주]\n최근, 충주의 수소 충전소에서 버스 폭발 사고가 난 가운데 충주시..."
3,20241227,"원-달러 환율 1,470원 돌파...금융위기 후 최고","달러,돌파,환율,금융위기,최고,앵커,권한대행,한덕수,대통령,권한,대행,탄핵,표결,달...",[앵커]\n한덕수 대통령 권한대행에 대한 탄핵안 표결을 앞두고 원-달러 환율이 무서...
4,20241226,"[비즈투데이] 현대차 '아이오닉 5', 최고 고도차 주행 전기차 부문서 기네스북 등재","현대차,아이오닉,등재,최고,고도차,주행,전기차,부문서,기네스북,현대자동차,아이오닉,...",현대자동차는 전용 전기차 '아이오닉 5'가 기네스북 '최고 고도차 주행 전기차 부문...

**Combining titles, keywords, and content**

In [ ]:
all_first_dfs = [
    df_first_Hyundai,
    df_first_Kbfg,
    df_first_Kia,
    df_first_Lgchem,
    df_first_Lgensol,
    df_first_Naver,
    df_first_PoscoHoldings,
    df_first_SamsungBiologics,
    df_first_Samsung,
    df_first_Skhynix
]

for i, df in enumerate(all_first_dfs):
    if not df.empty:
        df['content'] = df['제목'].astype(str) + ' ' + \
                        df['키워드'].astype(str) + ' ' + \
                        df['본문'].astype(str)
        df.drop(columns=['제목','키워드','본문'], errors='ignore', inplace=True)

In [ ]:
df_first_Hyundai.head()

         일자                                            content
0  20241230  [비즈투데이] 현대자동차 기아, '글로벌 통합 탄소 배출 정보 시스템' 구축 현대자...
1  20241230  올해 증시 혼조세로 마감...1년간 환율 180원 올라 증시,마감,1년,환율,증시,...
2  20241227  충주시 “수소버스 사고 수습 점검 강화” 충주시,수소버스,사고,수습,점검,강화,충주...
3  20241227  원-달러 환율 1,470원 돌파...금융위기 후 최고 달러,돌파,환율,금융위기,최고...
4  20241226  [비즈투데이] 현대차 '아이오닉 5', 최고 고도차 주행 전기차 부문서 기네스북 등...

In [ ]:
output_base_dir = '/content/drive/MyDrive/dataset'
df_first_folder = os.path.join(output_base_dir, 'df_first')

if not os.path.exists(df_first_folder):
    os.makedirs(df_first_folder)

In [ ]:
dataframes_to_save = {
    "df_first_Hyundai": df_first_Hyundai,
    "df_first_Kbfg": df_first_Kbfg,
    "df_first_Kia": df_first_Kia,
    "df_first_Lgchem": df_first_Lgchem,
    "df_first_Lgensol": df_first_Lgensol,
    "df_first_Naver": df_first_Naver,
    "df_first_PoscoHoldings": df_first_PoscoHoldings,
    "df_first_SamsungBiologics": df_first_SamsungBiologics,
    "df_first_Samsung": df_first_Samsung,
    "df_first_Skhynix": df_first_Skhynix,
}

**Save as csv file**

In [ ]:
for df_name, df in dataframes_to_save.items():
    df_path = os.path.join(df_first_folder, f"{df_name}.csv")
    df.to_csv(df_path, index=False, encoding='utf-8-sig')

#2군

In [ ]:
base_second_directory = '/content/drive/MyDrive/share_drive/박박박사/뉴스기사/2군'

base_second_1 = os.path.join(base_second_directory, '현대자동차2군.csv')
base_second_2 = os.path.join(base_second_directory, 'KB금융2군.csv')
base_second_3 = os.path.join(base_second_directory, '기아2군.csv')
base_second_4 = os.path.join(base_second_directory, 'LG화학2군.csv')
base_second_5 = os.path.join(base_second_directory, 'LG에너지솔루션2군.csv')
base_second_6 = os.path.join(base_second_directory, '네이버2군.csv')
base_second_7 = os.path.join(base_second_directory, 'POSCO홀딩스2군.csv')
base_second_8 = os.path.join(base_second_directory, '삼성바이오로직스2군.csv')
base_second_9 = os.path.join(base_second_directory, '삼성전자2군.csv')
base_second_10 = os.path.join(base_second_directory, 'SK하이닉스2군.csv')

**[colums_to_keep]: Method of not dropping other than the value for that color, already defined above**

In [ ]:
df_second_Hyundai = pd.read_csv(base_second_1)[columns_to_keep]
df_second_Kbfg = pd.read_csv(base_second_2)[columns_to_keep]
df_second_Kia = pd.read_csv(base_second_3)[columns_to_keep]
df_second_Lgchem = pd.read_csv(base_second_4)[columns_to_keep]
df_second_Lgensol = pd.read_csv(base_second_5)[columns_to_keep]
df_second_Naver = pd.read_csv(base_second_6)[columns_to_keep]
df_second_PoscoHoldings = pd.read_csv(base_second_7)[columns_to_keep]
df_second_SamsungBiologics = pd.read_csv(base_second_8)[columns_to_keep]
df_second_Samsung = pd.read_csv(base_second_9)[columns_to_keep]
df_second_Skhynix = pd.read_csv(base_second_10)[columns_to_keep]

In [ ]:
df_second_Hyundai.head()

,일자,제목,키워드,본문
0,20241230,[다산칼럼] 기업하기 힘든 나라,"기업,나라,대한민국,기업,나라,산업화,50년,선진국,반열,각종,규제,정서,포퓰리즘,...",대한민국은 기업하기 힘든 나라다. 산업화로 50년 만에 선진국 반열에 올라섰지만 각...
1,20241230,"“잘나가던 K자동차, 미국서 브레이크 걸리나” 트럼프 2기 앞두고 초긴장","K자동차,미국,2기,브레이크,트럼프,초긴장,멕시코,최대,산업타운,트럼프,태세,관세,...","멕시코 최대 韓산업타운 가보니 \n \n트럼프, 무관세협정 손볼 태세 \n원산지 규..."
2,20241230,[미리보는 이데일리 신문]B737-800 또 이상 국내 도입 101대 전수점검,"B737,전수점검,전수,점검,신문,일자,이데일리,기사,1면,B737,전수점검,전수,...",[이데일리 함지현 기자] 다음은 31일자 이데일리 신문 주요 기사다.\n\n△1면\...
3,20241230,고환율 계엄도 버틴 크래프톤 외국인이 모은 이유 있었네 [노정동의 어쩌다 투자자],"고환율,계엄,크래프톤,외국인,노정동,투자자,외국인,투자자,부진,코스피,지수,부진,게...",외국인 투자자들이 올해 코스피 지수 부진 속에서도 게임주(株)인 크래프톤을 꾸준히 ...
4,20241230,"연말 이어 연초도 '특근 풀가동' 현대차, 수출로 위기 돌파","연말,연초,특근,풀가동,현대차,수출,위기,돌파,생산체제,울산,공장,최대,생산,체제,...",울산공장 '최대 생산체제' 갖춰 \n해외수요 급증 SUV 하이브리드 \n매주 토요특...

In [ ]:
output_base_dir = '/content/drive/MyDrive/dataset'
df_score_folder = os.path.join(output_base_dir, 'df_score')

if not os.path.exists(df_score_folder):
    os.makedirs(df_score_folder)

**Combining titles, keywords, and content**

In [ ]:
all_second_dfs = [
    df_second_Hyundai,
    df_second_Kbfg,
    df_second_Kia,
    df_second_Lgchem,
    df_second_Lgensol,
    df_second_Naver,
    df_second_PoscoHoldings,
    df_second_SamsungBiologics,
    df_second_Samsung,
    df_second_Skhynix
]

for i, df in enumerate(all_second_dfs):
    if not df.empty:
        df['content'] = df['제목'].astype(str) + ' ' + \
                        df['키워드'].astype(str) + ' ' + \
                        df['본문'].astype(str)
        df.drop(columns=['제목','키워드','본문'], errors='ignore', inplace=True)

In [ ]:
df_second_Hyundai.head()

         일자                                            content
0  20241230  [다산칼럼] 기업하기 힘든 나라 기업,나라,대한민국,기업,나라,산업화,50년,선진국...
1  20241230  “잘나가던 K자동차, 미국서 브레이크 걸리나” 트럼프 2기 앞두고 초긴장 K자동차,...
2  20241230  [미리보는 이데일리 신문]B737-800 또 이상 국내 도입 101대 전수점검 B7...
3  20241230  고환율 계엄도 버틴 크래프톤 외국인이 모은 이유 있었네 [노정동의 어쩌다 투자자] ...
4  20241230  연말 이어 연초도 '특근 풀가동' 현대차, 수출로 위기 돌파 연말,연초,특근,풀가동...

In [ ]:
output_base_dir = '/content/drive/MyDrive/dataset'
df_second_folder = os.path.join(output_base_dir, 'df_second')

if not os.path.exists(df_second_folder):
    os.makedirs(df_second_folder)

In [ ]:
dataframes_to_save = {
    "df_second_Hyundai": df_second_Hyundai,
    "df_second_Kbfg": df_second_Kbfg,
    "df_second_Kia": df_second_Kia,
    "df_second_Lgchem": df_second_Lgchem,
    "df_second_Lgensol": df_second_Lgensol,
    "df_second_Naver": df_second_Naver,
    "df_second_PoscoHoldings": df_second_PoscoHoldings,
    "df_second_SamsungBiologics": df_second_SamsungBiologics,
    "df_second_Samsung": df_second_Samsung,
    "df_second_Skhynix": df_second_Skhynix,
}

**Save as csv file**

In [ ]:
for df_name, df in dataframes_to_save.items():
    df_path = os.path.join(df_second_folder, f"{df_name}.csv")
    df.to_csv(df_path, index=False, encoding='utf-8-sig')