#Install torch, scikit-learn, transformers, pandas

In [ ]:
!pip install transformers pandas scikit-learn torch

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.53.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.6.0+cu124)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.33.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.14.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.7.9)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.8 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 53.4 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 55.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 41.3 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.7 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.5 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 18.4 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.9 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.0 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 19.1 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

#Goggle drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#Import

In [ ]:
import os
import pandas as pd
import torch
import shutil
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from torch.nn.functional import softmax
from tqdm import tqdm

#Import Tokenization information and model

In [ ]:
BASE_DIR = '/content/drive/MyDrive/kobert_model'
LOAD_MODEL_PATH = "/content/drive/MyDrive/kobert_model/model_output/final_model_kobert_sentiment"

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(LOAD_MODEL_PATH)
model = AutoModelForSequenceClassification.from_pretrained(LOAD_MODEL_PATH)

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model.to(device)
model.eval()

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(32000, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
)

#Read first file

In [ ]:
base_path = '/content/drive/MyDrive/dataset/df_first/'

In [ ]:
df_first_Hyundai = pd.read_csv(base_path + 'df_first_Hyundai.csv')
df_first_Kbfg = pd.read_csv(base_path + 'df_first_Kbfg.csv')
df_first_Kia = pd.read_csv(base_path + 'df_first_Kia.csv')
df_first_Lgchem = pd.read_csv(base_path + 'df_first_Lgchem.csv')
df_first_Lgensol = pd.read_csv(base_path + 'df_first_Lgensol.csv')
df_first_Naver = pd.read_csv(base_path + 'df_first_Naver.csv')
df_first_PoscoHoldings = pd.read_csv(base_path + 'df_first_PoscoHoldings.csv')
df_first_Samsung = pd.read_csv(base_path + 'df_first_Samsung.csv')
df_first_SamsungBiologics = pd.read_csv(base_path + 'df_first_SamsungBiologics.csv')
df_first_Skhynix = pd.read_csv(base_path + 'df_first_Skhynix.csv')

In [ ]:
df_first_Hyundai.head()

         일자                                            content
0  20241230  [비즈투데이] 현대자동차 기아, '글로벌 통합 탄소 배출 정보 시스템' 구축 현대자...
1  20241230  올해 증시 혼조세로 마감...1년간 환율 180원 올라 증시,마감,1년,환율,증시,...
2  20241227  충주시 “수소버스 사고 수습 점검 강화” 충주시,수소버스,사고,수습,점검,강화,충주...
3  20241227  원-달러 환율 1,470원 돌파...금융위기 후 최고 달러,돌파,환율,금융위기,최고...
4  20241226  [비즈투데이] 현대차 '아이오닉 5', 최고 고도차 주행 전기차 부문서 기네스북 등...

#Predict first file

In [ ]:
def predict_sentiment(texts, model, tokenizer, device, batch_size=16):
    predictions = []
    probabilities = []

    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i: i + batch_size]

        inputs = tokenizer(batch_texts, truncation=True, padding=True,
                           max_length=512, return_tensors='pt').to(device)

        with torch.no_grad():
            outputs = model(**inputs)

        logits = outputs.logits
        probs = softmax(logits, dim=1).cpu().numpy()
        preds = torch.argmax(logits, dim=1).cpu().numpy()

        predictions.extend(preds)
        probabilities.extend(probs)

    return predictions, probabilities

In [ ]:
csv_files = {
    'Hyundai': 'df_first_Hyundai.csv',
    'Kbfg': 'df_first_Kbfg.csv',
    'Kia': 'df_first_Kia.csv',
    'Lgchem': 'df_first_Lgchem.csv',
    'Lgensol': 'df_first_Lgensol.csv',
    'Naver': 'df_first_Naver.csv',
    'PoscoHoldings': 'df_first_PoscoHoldings.csv',
    'Samsung': 'df_first_Samsung.csv',
    'SamsungBiologics': 'df_first_SamsungBiologics.csv',
    'Skhynix': 'df_first_Skhynix.csv'
}

base_path = '/content/drive/MyDrive/dataset/df_first/'
save_path = '/content/drive/MyDrive/result/first_file'

os.makedirs(save_path, exist_ok=True)

In [ ]:
for company, filename in tqdm(csv_files.items(), desc='기업별 뉴스 감성분석'):
    print(f"▶ {company} 처리 중...")

    try:
        df = pd.read_csv(os.path.join(base_path, filename))

        news_texts = df['content'].fillna("").tolist()
        dates = df['일자'].tolist()

        preds, probs = predict_sentiment(news_texts, model, tokenizer, device)

        result_df = pd.DataFrame({
            '일자': dates,
            'content': news_texts,
            '예측 라벨': preds,
            '부정 확률 (0)': [f"{p[0]:.3f}" for p in probs],
            '긍정 확률 (1)': [f"{p[1]:.3f}" for p in probs],
            '감성': ['긍정' if label == 1 else '부정' for label in preds]
        })

        output_file = os.path.join(save_path, f'{company}_sentiment_result.csv')
        result_df.to_csv(output_file, index=False, encoding='utf-8-sig')
        print(f"{company} 완료 → 저장: {output_file}")

    except Exception as e:
        print(f"{company} 처리 중 오류 발생: {e}")

기업별 뉴스 감성분석:   0%|          | 0/10 [00:00<?, ?it/s]

▶ Hyundai 처리 중...

기업별 뉴스 감성분석:  10%|█         | 1/10 [01:39<14:53, 99.23s/it]

Hyundai 완료 → 저장: /content/drive/MyDrive/result/first_file/Hyundai_sentiment_result.csv
▶ Kbfg 처리 중...

기업별 뉴스 감성분석:  20%|██        | 2/10 [01:43<05:45, 43.25s/it]

Kbfg 완료 → 저장: /content/drive/MyDrive/result/first_file/Kbfg_sentiment_result.csv
▶ Kia 처리 중...

기업별 뉴스 감성분석:  30%|███       | 3/10 [02:31<05:17, 45.41s/it]

Kia 완료 → 저장: /content/drive/MyDrive/result/first_file/Kia_sentiment_result.csv
▶ Lgchem 처리 중...

기업별 뉴스 감성분석:  40%|████      | 4/10 [02:39<03:04, 30.74s/it]

Lgchem 완료 → 저장: /content/drive/MyDrive/result/first_file/Lgchem_sentiment_result.csv
▶ Lgensol 처리 중...

기업별 뉴스 감성분석:  50%|█████     | 5/10 [02:56<02:09, 25.93s/it]

Lgensol 완료 → 저장: /content/drive/MyDrive/result/first_file/Lgensol_sentiment_result.csv
▶ Naver 처리 중...

기업별 뉴스 감성분석:  60%|██████    | 6/10 [03:26<01:48, 27.00s/it]

Naver 완료 → 저장: /content/drive/MyDrive/result/first_file/Naver_sentiment_result.csv
▶ PoscoHoldings 처리 중...

기업별 뉴스 감성분석:  70%|███████   | 7/10 [03:37<01:06, 22.07s/it]

PoscoHoldings 완료 → 저장: /content/drive/MyDrive/result/first_file/PoscoHoldings_sentiment_result.csv
▶ Samsung 처리 중...

기업별 뉴스 감성분석:  80%|████████  | 8/10 [06:00<02:01, 60.55s/it]

Samsung 완료 → 저장: /content/drive/MyDrive/result/first_file/Samsung_sentiment_result.csv
▶ SamsungBiologics 처리 중...

기업별 뉴스 감성분석:  90%|█████████ | 9/10 [06:05<00:43, 43.03s/it]

SamsungBiologics 완료 → 저장: /content/drive/MyDrive/result/first_file/SamsungBiologics_sentiment_result.csv
▶ Skhynix 처리 중...

기업별 뉴스 감성분석: 100%|██████████| 10/10 [07:14<00:00, 43.49s/it]

Skhynix 완료 → 저장: /content/drive/MyDrive/result/first_file/Skhynix_sentiment_result.csv

In [ ]:
def copy_first_file(base_path,destination_path):
  folder_name=os.path.basename(base_path)
  destination_path=os.path.join(destination_path,folder_name)

  shutil.copytree(base_path,destination_path)

In [ ]:
base_path='/content/drive/MyDrive/result/first_file'
destination_path='/content/drive/MyDrive/share_drive/박박박사/emotion_analysis'

copy_first_file(base_path,destination_path)

#Read second file

In [ ]:
base_path = '/content/drive/MyDrive/dataset/df_second/'

In [ ]:
df_second_Hyundai = pd.read_csv(base_path + 'df_second_Hyundai.csv')
df_second_Kbfg = pd.read_csv(base_path + 'df_second_Kbfg.csv')
df_second_Kia = pd.read_csv(base_path + 'df_second_Kia.csv')
df_second_Lgchem = pd.read_csv(base_path + 'df_second_Lgchem.csv')
df_second_Lgensol = pd.read_csv(base_path + 'df_second_Lgensol.csv')
df_second_Naver = pd.read_csv(base_path + 'df_second_Naver.csv')
df_second_PoscoHoldings = pd.read_csv(base_path + 'df_second_PoscoHoldings.csv')
df_second_Samsung = pd.read_csv(base_path + 'df_second_Samsung.csv')
df_second_SamsungBiologics = pd.read_csv(base_path + 'df_second_SamsungBiologics.csv')
df_second_Skhynix = pd.read_csv(base_path + 'df_second_Skhynix.csv')

In [ ]:
df_second_Hyundai.head()

         일자                                            content
0  20241230  [다산칼럼] 기업하기 힘든 나라 기업,나라,대한민국,기업,나라,산업화,50년,선진국...
1  20241230  “잘나가던 K자동차, 미국서 브레이크 걸리나” 트럼프 2기 앞두고 초긴장 K자동차,...
2  20241230  [미리보는 이데일리 신문]B737-800 또 이상 국내 도입 101대 전수점검 B7...
3  20241230  고환율 계엄도 버틴 크래프톤 외국인이 모은 이유 있었네 [노정동의 어쩌다 투자자] ...
4  20241230  연말 이어 연초도 '특근 풀가동' 현대차, 수출로 위기 돌파 연말,연초,특근,풀가동...

#Predict second file

In [ ]:
csv_files = {
    'Hyundai': 'df_second_Hyundai.csv',
    'Kbfg': 'df_second_Kbfg.csv',
    'Kia': 'df_second_Kia.csv',
    'Lgchem': 'df_second_Lgchem.csv',
    'Lgensol': 'df_second_Lgensol.csv',
    'Naver': 'df_second_Naver.csv',
    'PoscoHoldings': 'df_second_PoscoHoldings.csv',
    'Samsung': 'df_second_Samsung.csv',
    'SamsungBiologics': 'df_second_SamsungBiologics.csv',
    'Skhynix': 'df_second_Skhynix.csv'
}

base_path = '/content/drive/MyDrive/dataset/df_second/'
save_path = '/content/drive/MyDrive/result/second_file'

os.makedirs(save_path, exist_ok=True)

In [ ]:
for company, filename in tqdm(csv_files.items(), desc='기업별 뉴스 감성분석'):
    print(f"▶ {company} 처리 중...")

    try:
        df = pd.read_csv(os.path.join(base_path, filename))

        news_texts = df['content'].fillna("").tolist()
        dates = df['일자'].tolist()

        preds, probs = predict_sentiment(news_texts, model, tokenizer, device)

        result_df = pd.DataFrame({
            '일자': dates,
            'content': news_texts,
            '예측 라벨': preds,
            '부정 확률 (0)': [f"{p[0]:.3f}" for p in probs],
            '긍정 확률 (1)': [f"{p[1]:.3f}" for p in probs],
            '감성': ['긍정' if label == 1 else '부정' for label in preds]
        })

        output_file = os.path.join(save_path, f'{company}_sentiment_result.csv')
        result_df.to_csv(output_file, index=False, encoding='utf-8-sig')
        print(f"{company} 완료 → 저장: {output_file}")

    except Exception as e:
        print(f"{company} 처리 중 오류 발생: {e}")

기업별 뉴스 감성분석:   0%|          | 0/10 [00:00<?, ?it/s]

▶ Hyundai 처리 중...

기업별 뉴스 감성분석:  10%|█         | 1/10 [32:02<4:48:20, 1922.30s/it]

Hyundai 완료 → 저장: /content/drive/MyDrive/result/second_file/Hyundai_sentiment_result.csv
▶ Kbfg 처리 중...

기업별 뉴스 감성분석:  20%|██        | 2/10 [35:50<2:03:26, 925.83s/it]

Kbfg 완료 → 저장: /content/drive/MyDrive/result/second_file/Kbfg_sentiment_result.csv
▶ Kia 처리 중...

기업별 뉴스 감성분석:  30%|███       | 3/10 [55:28<2:01:27, 1041.13s/it]

Kia 완료 → 저장: /content/drive/MyDrive/result/second_file/Kia_sentiment_result.csv
▶ Lgchem 처리 중...

기업별 뉴스 감성분석:  40%|████      | 4/10 [1:01:20<1:16:53, 768.94s/it]

Lgchem 완료 → 저장: /content/drive/MyDrive/result/second_file/Lgchem_sentiment_result.csv
▶ Lgensol 처리 중...

기업별 뉴스 감성분석:  50%|█████     | 5/10 [1:18:02<1:11:04, 852.90s/it]

Lgensol 완료 → 저장: /content/drive/MyDrive/result/second_file/Lgensol_sentiment_result.csv
▶ Naver 처리 중...

기업별 뉴스 감성분석:  60%|██████    | 6/10 [1:37:10<1:03:33, 953.42s/it]

Naver 완료 → 저장: /content/drive/MyDrive/result/second_file/Naver_sentiment_result.csv
▶ PoscoHoldings 처리 중...

기업별 뉴스 감성분석:  70%|███████   | 7/10 [1:44:16<39:02, 780.92s/it]

PoscoHoldings 완료 → 저장: /content/drive/MyDrive/result/second_file/PoscoHoldings_sentiment_result.csv
▶ Samsung 처리 중...

기업별 뉴스 감성분석:  80%|████████  | 8/10 [2:32:25<48:23, 1451.82s/it]

Samsung 완료 → 저장: /content/drive/MyDrive/result/second_file/Samsung_sentiment_result.csv
▶ SamsungBiologics 처리 중...

기업별 뉴스 감성분석:  90%|█████████ | 9/10 [2:39:55<18:58, 1138.80s/it]

SamsungBiologics 완료 → 저장: /content/drive/MyDrive/result/second_file/SamsungBiologics_sentiment_result.csv
▶ Skhynix 처리 중...

기업별 뉴스 감성분석: 100%|██████████| 10/10 [3:04:12<00:00, 1105.24s/it]

Skhynix 완료 → 저장: /content/drive/MyDrive/result/second_file/Skhynix_sentiment_result.csv

In [ ]:
def copy_second_file(base_path,destination_path):
  folder_name=os.path.basename(base_path)
  destination_path=os.path.join(destination_path,folder_name)

  shutil.copytree(base_path,destination_path)

In [ ]:
base_path='/content/drive/MyDrive/result/second_file'
destination_path='/content/drive/MyDrive/share_drive/박박박사/emotion_analysis'

copy_second_file(base_path,destination_path)

#Read score file

In [ ]:
base_path = '/content/drive/MyDrive/dataset/df_score/'

In [ ]:
df_score_Hyundai = pd.read_csv(base_path + 'df_score_Hyundai.csv')
df_score_Kbfg = pd.read_csv(base_path + 'df_score_Kbfg.csv')
df_score_Kia = pd.read_csv(base_path + 'df_score_Kia.csv')
df_score_Lgchem = pd.read_csv(base_path + 'df_score_Lgchem.csv')
df_score_Lgensol = pd.read_csv(base_path + 'df_score_Lgensol.csv')
df_score_Naver = pd.read_csv(base_path + 'df_score_Naver.csv')
df_score_PoscoHoldings = pd.read_csv(base_path + 'df_score_PoscoHoldings.csv')
df_score_Samsung = pd.read_csv(base_path + 'df_score_Samsung.csv')
df_score_SamsungBiologics = pd.read_csv(base_path + 'df_score_SamsungBiologics.csv')
df_score_Skhynix = pd.read_csv(base_path + 'df_score_Skhynix.csv')

In [ ]:
df_score_Hyundai.head()

           날짜   점수        요일  공휴일여부
0  2022-01-27  109  Thursday      0
1  2022-01-28   73    Friday      0
2  2022-01-29   12  Saturday      0
3  2022-01-30    5    Sunday      0
4  2022-01-31   18    Monday      1