In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
first_path ='/content/drive/MyDrive/share_drive/result/first_file'
second_path ='/content/drive/MyDrive/share_drive/result/second_file'
score_path ='/content/drive/MyDrive/dataset/df_score'

#감성분석 후 데이터가공_first

In [ ]:
df_first_Hyundai = pd.read_csv(f'{first_path}/Hyundai_sentiment_result.csv').drop('content', axis=1)
df_first_Kbfg = pd.read_csv(f'{first_path}/Kbfg_sentiment_result.csv').drop('content', axis=1)
df_first_Kia = pd.read_csv(f'{first_path}/Kia_sentiment_result.csv').drop('content', axis=1)
df_first_Lgchem = pd.read_csv(f'{first_path}/Lgchem_sentiment_result.csv').drop('content', axis=1)
df_first_Lgensol = pd.read_csv(f'{first_path}/Lgensol_sentiment_result.csv').drop('content', axis=1)
df_first_Naver = pd.read_csv(f'{first_path}/Naver_sentiment_result.csv').drop('content', axis=1)
df_first_PoscoHoldings = pd.read_csv(f'{first_path}/PoscoHoldings_sentiment_result.csv').drop('content', axis=1)
df_first_SamsungBiologics = pd.read_csv(f'{first_path}/SamsungBiologics_sentiment_result.csv').drop('content', axis=1)
df_first_Samsung = pd.read_csv(f'{first_path}/Samsung_sentiment_result.csv').drop('content', axis=1)
df_first_Skhynix = pd.read_csv(f'{first_path}/Skhynix_sentiment_result.csv').drop('content', axis=1)

In [ ]:
df_first_Hyundai.head()

         일자  부정 확률 (0)  긍정 확률 (1)  감성
0  20220127   0.253667   0.746333  긍정
1  20220128   0.463000   0.537000  긍정
2  20220131   0.001000   0.999000  긍정
3  20220201   0.001000   0.999000  긍정
4  20220202   0.269800   0.730200  긍정

In [ ]:
avg_emotion_Hyundai = df_first_Hyundai.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Hyundai['감성'] = avg_emotion_Hyundai.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_first_Hyundai = avg_emotion_Hyundai

avg_emotion_Kbfg = df_first_Kbfg.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Kbfg['감성'] = avg_emotion_Kbfg.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_first_Kbfg = avg_emotion_Kbfg

avg_emotion_Kia = df_first_Kia.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Kia['감성'] = avg_emotion_Kia.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_first_Kia = avg_emotion_Kia

avg_emotion_Lgchem = df_first_Lgchem.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Lgchem['감성'] = avg_emotion_Lgchem.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_first_Lgchem = avg_emotion_Lgchem

avg_emotion_Lgensol = df_first_Lgensol.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Lgensol['감성'] = avg_emotion_Lgensol.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_first_Lgensol = avg_emotion_Lgensol

avg_emotion_Naver = df_first_Naver.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Naver['감성'] = avg_emotion_Naver.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_first_Naver = avg_emotion_Naver

avg_emotion_PoscoHoldings = df_first_PoscoHoldings.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_PoscoHoldings['감성'] = avg_emotion_PoscoHoldings.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_first_PoscoHoldings = avg_emotion_PoscoHoldings

avg_emotion_SamsungBiologics = df_first_SamsungBiologics.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_SamsungBiologics['감성'] = avg_emotion_SamsungBiologics.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_first_SamsungBiologics = avg_emotion_SamsungBiologics

avg_emotion_Samsung = df_first_Samsung.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Samsung['감성'] = avg_emotion_Samsung.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_first_Samsung = avg_emotion_Samsung

avg_emotion_Skhynix = df_first_Skhynix.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Skhynix['감성'] = avg_emotion_Skhynix.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_first_Skhynix = avg_emotion_Skhynix

In [ ]:
df_first_Hyundai.head().round(3)

         일자  부정 확률 (0)  긍정 확률 (1)  감성
0  20220127      0.254      0.746  긍정
1  20220128      0.463      0.537  긍정
2  20220131      0.001      0.999  긍정
3  20220201      0.001      0.999  긍정
4  20220202      0.270      0.730  긍정

#감성분석 후 데이터가공_second

In [ ]:
df_second_Hyundai = pd.read_csv(f'{second_path}/Hyundai_sentiment_result.csv').drop('content', axis=1)
df_second_Kbfg = pd.read_csv(f'{second_path}/Kbfg_sentiment_result.csv').drop('content', axis=1)
df_second_Kia = pd.read_csv(f'{second_path}/Kia_sentiment_result.csv').drop('content', axis=1)
df_second_Lgchem = pd.read_csv(f'{second_path}/Lgchem_sentiment_result.csv').drop('content', axis=1)
df_second_Lgensol = pd.read_csv(f'{second_path}/Lgensol_sentiment_result.csv').drop('content', axis=1)
df_second_Naver = pd.read_csv(f'{second_path}/Naver_sentiment_result.csv').drop('content', axis=1)
df_second_PoscoHoldings = pd.read_csv(f'{second_path}/PoscoHoldings_sentiment_result.csv').drop('content', axis=1)
df_second_SamsungBiologics = pd.read_csv(f'{second_path}/SamsungBiologics_sentiment_result.csv').drop('content', axis=1)
df_second_Samsung = pd.read_csv(f'{second_path}/Samsung_sentiment_result.csv').drop('content', axis=1)
df_second_Skhynix = pd.read_csv(f'{second_path}/Skhynix_sentiment_result.csv').drop('content', axis=1)

In [ ]:
df_second_Hyundai.head()

         일자  예측 라벨  부정 확률 (0)  긍정 확률 (1)  감성
0  20241230      1      0.181      0.819  긍정
1  20241230      1      0.349      0.651  긍정
2  20241230      1      0.432      0.568  긍정
3  20241230      1      0.361      0.639  긍정
4  20241230      1      0.495      0.505  긍정

In [ ]:
avg_emotion_Hyundai_sec = df_second_Hyundai.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Hyundai_sec['감성'] = avg_emotion_Hyundai_sec.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_second_Hyundai = avg_emotion_Hyundai_sec

avg_emotion_Kbfg_sec = df_second_Kbfg.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Kbfg_sec['감성'] = avg_emotion_Kbfg_sec.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_second_Kbfg = avg_emotion_Kbfg_sec

avg_emotion_Kia_sec = df_second_Kia.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Kia_sec['감성'] = avg_emotion_Kia_sec.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_second_Kia = avg_emotion_Kia_sec

avg_emotion_Lgchem_sec = df_second_Lgchem.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Lgchem_sec['감성'] = avg_emotion_Lgchem_sec.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_second_Lgchem = avg_emotion_Lgchem_sec

avg_emotion_Lgensol_sec = df_second_Lgensol.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Lgensol_sec['감성'] = avg_emotion_Lgensol_sec.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_second_Lgensol = avg_emotion_Lgensol_sec

avg_emotion_Naver_sec = df_second_Naver.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Naver_sec['감성'] = avg_emotion_Naver_sec.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_second_Naver = avg_emotion_Naver_sec

avg_emotion_PoscoHoldings_sec = df_second_PoscoHoldings.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_PoscoHoldings_sec['감성'] = avg_emotion_PoscoHoldings_sec.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_second_PoscoHoldings = avg_emotion_PoscoHoldings_sec

avg_emotion_SamsungBiologics_sec = df_second_SamsungBiologics.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_SamsungBiologics_sec['감성'] = avg_emotion_SamsungBiologics_sec.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_second_SamsungBiologics = avg_emotion_SamsungBiologics_sec

avg_emotion_Samsung_sec = df_second_Samsung.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Samsung_sec['감성'] = avg_emotion_Samsung_sec.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_second_Samsung = avg_emotion_Samsung_sec

avg_emotion_Skhynix_sec = df_second_Skhynix.groupby('일자').agg({
    '부정 확률 (0)': 'mean',
    '긍정 확률 (1)': 'mean'
}).reset_index()
avg_emotion_Skhynix_sec['감성'] = avg_emotion_Skhynix_sec.apply(lambda row: '긍정' if row['긍정 확률 (1)'] >= row['부정 확률 (0)'] else '부정', axis=1)
df_second_Skhynix = avg_emotion_Skhynix_sec

In [ ]:
df_second_Hyundai.head().round(3)

         일자  부정 확률 (0)  긍정 확률 (1)  감성
0  20220127      0.265      0.735  긍정
1  20220128      0.298      0.702  긍정
2  20220129      0.614      0.386  부정
3  20220130      0.347      0.653  긍정
4  20220131      0.261      0.739  긍정

In [ ]:
first_save_path = '/content/drive/MyDrive/share_drive/박박박사/emotion/first_team'
second_save_path = '/content/drive/MyDrive/share_drive/박박박사/emotion/second_team'

In [ ]:
df_first_Hyundai.to_csv(os.path.join(first_save_path, 'Hyundai_aggregated_sentiment.csv'), index=False)
df_first_Kbfg.to_csv(os.path.join(first_save_path, 'Kbfg_aggregated_sentiment.csv'), index=False)
df_first_Kia.to_csv(os.path.join(first_save_path, 'Kia_aggregated_sentiment.csv'), index=False)
df_first_Lgchem.to_csv(os.path.join(first_save_path, 'Lgchem_aggregated_sentiment.csv'), index=False)
df_first_Lgensol.to_csv(os.path.join(first_save_path, 'Lgensol_aggregated_sentiment.csv'), index=False)
df_first_Naver.to_csv(os.path.join(first_save_path, 'Naver_aggregated_sentiment.csv'), index=False)
df_first_PoscoHoldings.to_csv(os.path.join(first_save_path, 'PoscoHoldings_aggregated_sentiment.csv'), index=False)
df_first_SamsungBiologics.to_csv(os.path.join(first_save_path, 'SamsungBiologics_aggregated_sentiment.csv'), index=False)
df_first_Samsung.to_csv(os.path.join(first_save_path, 'Samsung_aggregated_sentiment.csv'), index=False)
df_first_Skhynix.to_csv(os.path.join(first_save_path, 'Skhynix_aggregated_sentiment.csv'), index=False)

df_second_Hyundai.to_csv(os.path.join(second_save_path, 'Hyundai_aggregated_sentiment.csv'), index=False)
df_second_Kbfg.to_csv(os.path.join(second_save_path, 'Kbfg_aggregated_sentiment.csv'), index=False)
df_second_Kia.to_csv(os.path.join(second_save_path, 'Kia_aggregated_sentiment.csv'), index=False)
df_second_Lgchem.to_csv(os.path.join(second_save_path, 'Lgchem_aggregated_sentiment.csv'), index=False)
df_second_Lgensol.to_csv(os.path.join(second_save_path, 'Lgensol_aggregated_sentiment.csv'), index=False)
df_second_Naver.to_csv(os.path.join(second_save_path, 'Naver_aggregated_sentiment.csv'), index=False)
df_second_PoscoHoldings.to_csv(os.path.join(second_save_path, 'PoscoHoldings_aggregated_sentiment.csv'), index=False)
df_second_SamsungBiologics.to_csv(os.path.join(second_save_path, 'SamsungBiologics_aggregated_sentiment.csv'), index=False)
df_second_Samsung.to_csv(os.path.join(second_save_path, 'Samsung_aggregated_sentiment.csv'), index=False)
df_second_Skhynix.to_csv(os.path.join(second_save_path, 'Skhynix_aggregated_sentiment.csv'), index=False)